apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "tconn2"
  annotations:
    github.com/project-slug: danielsollondon/backstack
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
